import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.ContingencyTablesLemmaCanonicalLaneLean.ContingencyTablesPackage
import HautevilleHouse.ContingencyTablesLemmaCanonicalLaneLean.IndependenceTestPackage
import HautevilleHouse.ContingencyTablesLemmaCanonicalLaneLean.LogLinearModelsPackage
import HautevilleHouse.ContingencyTablesLemmaCanonicalLaneLean.AdmissibleClass
import HautevilleHouse.ContingencyTablesLemmaCanonicalLaneLean.BridgeLemmas
import HautevilleHouse.ContingencyTablesLemmaCanonicalLaneLean.GateLemmas
import HautevilleHouse.ContingencyTablesLemmaCanonicalLaneLean.ContingencyClosure

namespace HautevilleHouse
namespace ContingencyTablesLemmaCanonicalLaneLean

end ContingencyTablesLemmaCanonicalLaneLean
end HautevilleHouse